services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jetdb
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
  redis:
    image: redis:latest
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    ports:
      - 6379:6379

volumes:
  postgres_data:
